import z from "zod";
import { zDecimal, zSmallint, zTimestamps } from "./zod_utils.js";

export const dailyComplianceMandatoryZod = z.object({
	userId: z.uuid(),
	intakePercentage: zDecimal(5, 2, 0, 100),
	date: z.iso.date(),
	dailyShieldOpeningBalance: zSmallint(0),
	dailyShieldClosingBalance: zSmallint(0),
	dailyShieldUsed: z.boolean(),
});

export const dailyComplianceAutoGeneratedZod = z.object({
	id: z.uuid(),
});

export const dailyComplianceOptionalZod = z.object({});

export const dailyComplianceCreateInputZod = dailyComplianceMandatoryZod
	.omit({ userId: true })
	.extend(dailyComplianceOptionalZod.partial().shape);
export type DailyComplianceCreateInput = z.infer<typeof dailyComplianceCreateInputZod>;

export const dailyComplianceUpdateInputZod = dailyComplianceMandatoryZod
	.extend(dailyComplianceOptionalZod.shape)
	.extend(zTimestamps)
	.omit({ userId: true })
	.partial();
export type DailyComplianceUpdateInput = z.infer<typeof dailyComplianceUpdateInputZod>;

export const dailyComplianceSelectAllZod = dailyComplianceMandatoryZod
	.extend(dailyComplianceOptionalZod.shape)
	.extend(zTimestamps)
	.extend(dailyComplianceAutoGeneratedZod.shape);
export type DailyComplianceSelectAll = z.infer<typeof dailyComplianceSelectAllZod>;

export const dailyComplianceGetByIdZod = dailyComplianceAutoGeneratedZod;
export type DailyComplianceGetByIdInput = z.infer<typeof dailyComplianceGetByIdZod>;

export const dailyComplianceGetByUserZod = z.object({
	userId: z.uuid(),
});
export type DailyComplianceGetByUserInput = z.infer<typeof dailyComplianceGetByUserZod>;

export const dailyComplianceGetByDateRangeZod = z.object({
	userId: z.uuid(),
	startDate: z.iso.date(),
	endDate: z.iso.date(),
});
export type DailyComplianceGetByDateRangeInput = z.infer<typeof dailyComplianceGetByDateRangeZod>;

export const dailyComplianceDeleteZod = dailyComplianceAutoGeneratedZod;
export type DailyComplianceDeleteInput = z.infer<typeof dailyComplianceDeleteZod>;
