import { rewardsTransactionTypeZod } from "@zod-schemas/enums.zod.js";
import z from "zod";
import { zTimestamps } from "./zod_utils.js";

export const rewardsLedgerMandatoryZod = z.object({
	userId: z.uuid(),
	intakeLogId: z.uuid().nullable(),
	amountCoins: z.number().int(),
	amountShields: z.number().int(),
	reason: z.string(),
	transactionType: rewardsTransactionTypeZod,
});

export const rewardsLedgerAutoGeneratedZod = z.object({
	rewardLedgerId: z.ulid(),
});

export const rewardsLedgerSelectAllZod = rewardsLedgerMandatoryZod
	.extend(rewardsLedgerAutoGeneratedZod.shape)
	.extend(zTimestamps);

export type RewardsLedgerSelectAll = z.infer<typeof rewardsLedgerSelectAllZod>;

export const rewardsLedgerGetByUserInputZod = z.object({
	itemType: z.enum(["coins", "shields"]).optional(),
	limit: z.number().int().positive().max(100).default(50),
	cursor: z.ulid().nullable(),
});

export type RewardsLedgerGetByUserInput = z.infer<typeof rewardsLedgerGetByUserInputZod>;
