import z from "zod";
import { zInteger, zSmallint, zTimestamps } from "./zod_utils.js";

export const userStatsMandatoryZod = z.object({
	userId: z.uuid(),
	coinsBalance: zSmallint(0).default(0),
	currentStreak: zInteger(0),
	currentStreakShieldsUsed: zSmallint(0),
	longestStreak: zInteger(0),
	longestStreakShieldsUsed: zSmallint(0),
	shieldsBalance: zSmallint(0).default(0),
});

export const userStatsAutoGeneratedZod = z.object({});

export const userStatsOptionalZod = z.object({});

export const userStatsSelectAllZod = userStatsMandatoryZod
	.extend(userStatsOptionalZod.shape)
	.extend(zTimestamps);
export type UserStatsSelectAll = z.infer<typeof userStatsSelectAllZod>;

export const userStatsGetByUserZod = z.object({
	userId: z.uuid(),
});
export type UserStatsGetByUserInput = z.infer<typeof userStatsGetByUserZod>;
