import { themeSettingZod } from "@zod-schemas/enums.zod.js";
import z from "zod";
import { CoercedCanonicalTimezoneSchema } from "zod-timezone-validation";
import { zString, zTimestamps } from "./zod_utils.js";

export const userMandatoryZod = z.object({
  email: z.email(),
  name: zString,
  themeSetting: themeSettingZod.default("light")
});

const userAutoGeneratedZod = z.object({
  id: z.uuid(),
  emailVerified: z.boolean(),
});

export const userOptionalZod = z.object({
  image: z.url().nullable(),
  timezone: CoercedCanonicalTimezoneSchema.nullable(),
});

export const notificationPreferencesZod = z.object({
  emailNotification: z.boolean(),
  pushNotification: z.boolean(),
});

export const userCreateInputZod = userMandatoryZod.extend(userOptionalZod.partial().shape);
export type UserCreateInput = z.infer<typeof userCreateInputZod>;

export const userUpdateInputZod = userMandatoryZod
  .extend(userOptionalZod.shape)
  .omit({ 
    email: true,
  })
  .partial();
export type UserUpdateInput = z.infer<typeof userUpdateInputZod>;

export const userSelectAllZod = userMandatoryZod
	.extend(userOptionalZod.shape)
	.extend(zTimestamps)
	.extend(userAutoGeneratedZod.shape)
	.extend({ notificationPreferences: notificationPreferencesZod });
export type UserSelectAll = z.infer<typeof userSelectAllZod>;

export const userGetByIdInputZod = userAutoGeneratedZod;
export type UserGetByIdInput = z.infer<typeof userGetByIdInputZod>;