import z from "zod";
import { userIntakeStatusZod } from "./enums.zod.js";
import { zString, zTimeEpoch, zTimestamps, zTimezone } from "./zod_utils.js";

export const userIntakeLogMandatoryZod = z.object({
	userId: z.uuid(),
	supplementId: z.uuid(),
	status: userIntakeStatusZod,
	scheduledFor: zTimeEpoch,
	actualAt: zTimeEpoch,
	logTimezone: zTimezone,
});

export const userIntakeLogAutoGeneratedZod = z.object({
	id: z.uuid(),
});

export const userIntakeLogOptionalZod = z.object({
	reason: zString.nullable(),
});

export const userIntakeLogCreateInputZod = userIntakeLogMandatoryZod
	.omit({ userId: true })
	.extend(userIntakeLogOptionalZod.partial().shape);
export type UserIntakeLogCreateInput = z.infer<typeof userIntakeLogCreateInputZod>;

export const userIntakeLogUpdateInputZod = userIntakeLogMandatoryZod
	.extend(userIntakeLogOptionalZod.shape)
	.extend(zTimestamps)
	.omit({ userId: true })
	.partial();
export type UserIntakeLogUpdateInput = z.infer<typeof userIntakeLogUpdateInputZod>;

export const userIntakeLogSelectAllZod = userIntakeLogMandatoryZod
	.extend(userIntakeLogOptionalZod.shape)
	.extend(zTimestamps)
	.extend(userIntakeLogAutoGeneratedZod.shape);
export type UserIntakeLogSelectAll = z.infer<typeof userIntakeLogSelectAllZod>;

export const userIntakeLogGetByIdZod = userIntakeLogAutoGeneratedZod;
export type UserIntakeLogGetByIdInput = z.infer<typeof userIntakeLogGetByIdZod>;

export const userIntakeLogGetByUserZod = z.object({
	userId: z.uuid(),
});
export type UserIntakeLogGetByUserInput = z.infer<typeof userIntakeLogGetByUserZod>;

export const userIntakeLogGetBySupplementZod = z.object({
	supplementId: z.uuid(),
});
export type UserIntakeLogGetBySupplementInput = z.infer<typeof userIntakeLogGetBySupplementZod>;

export const userIntakeLogDeleteZod = userIntakeLogAutoGeneratedZod.extend({
	logTimezone: userIntakeLogMandatoryZod.shape.logTimezone,
	scheduledFor: userIntakeLogMandatoryZod.shape.scheduledFor
});
export type UserIntakeLogDeleteInput = z.infer<typeof userIntakeLogDeleteZod>;
