import z from "zod";
import { daysOfWeekZod } from "./enums.zod.js";
import { zSmallint, zString, zTimestamps } from "./zod_utils.js";

export const userStackMandatoryZod = z.object({
	userId: z.uuid(),
	name: zString,
	instructions: z.array(zString).default([]),
	isActive: z.boolean(),
	dosage: zSmallint(1),
	unit: zString,
	days: daysOfWeekZod,
	timesOfDay: z.array(zString),
});

export const userStackAutoGeneratedZod = z.object({
	id: z.uuid(),
});

export const userStackOptionalZod = z.object({
	imageUrl: z.url().nullable(),
});

export const userStackCreateInputZod = userStackMandatoryZod
	.omit({ userId: true })
	.extend(userStackOptionalZod.partial().shape);
export type UserStackCreateInput = z.infer<typeof userStackCreateInputZod>;

export const userStackUpdateInputZod = userStackMandatoryZod
	.extend(userStackOptionalZod.shape)
	.extend(zTimestamps)
	.omit({ userId: true })
	.partial();
export type UserStackUpdateInput = z.infer<typeof userStackUpdateInputZod>;

export const userStackSelectAllZod = userStackMandatoryZod
	.extend(userStackOptionalZod.shape)
	.extend(zTimestamps)
	.extend(userStackAutoGeneratedZod.shape);
export type UserStackSelectAll = z.infer<typeof userStackSelectAllZod>;

export const userStackGetByIdZod = userStackAutoGeneratedZod;
export type UserStackGetByIdInput = z.infer<typeof userStackGetByIdZod>;

export const userStackGetByUserZod = z.object({
	userId: z.uuid(),
});
export type UserStackGetByUserInput = z.infer<typeof userStackGetByUserZod>;

export const userStackDeleteZod = userStackAutoGeneratedZod;
export type UserStackDeleteInput = z.infer<typeof userStackDeleteZod>;
