import z from "zod";
import { userAdherenceStatusZod } from "./enums.zod.js";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

export const userAdherenceLogMandatoryZod = z.object({
	userId: z.uuid(),
	supplementId: z.uuid(),
	status: userAdherenceStatusZod,
	scheduledFor: zTimeEpoch,
	actualAt: zTimeEpoch,
	timeZoneOffset: zSmallint(),
});

export const userAdherenceLogAutoGeneratedZod = z.object({
	id: z.uuid(),
});

export const userAdherenceLogOptionalZod = z.object({
	reason: zString.nullable(),
});

export const userAdherenceLogCreateInputZod = userAdherenceLogMandatoryZod
	.omit({ userId: true })
	.extend(userAdherenceLogOptionalZod.partial().shape);
export type UserAdherenceLogCreateInput = z.infer<typeof userAdherenceLogCreateInputZod>;

export const userAdherenceLogUpdateInputZod = userAdherenceLogMandatoryZod
	.extend(userAdherenceLogOptionalZod.shape)
	.extend(zTimestamps)
	.omit({ userId: true })
	.partial();
export type UserAdherenceLogUpdateInput = z.infer<typeof userAdherenceLogUpdateInputZod>;

export const userAdherenceLogSelectAllZod = userAdherenceLogMandatoryZod
	.extend(userAdherenceLogOptionalZod.shape)
	.extend(zTimestamps)
	.extend(userAdherenceLogAutoGeneratedZod.shape);
export type UserAdherenceLogSelectAll = z.infer<typeof userAdherenceLogSelectAllZod>;

export const userAdherenceLogGetByIdZod = userAdherenceLogAutoGeneratedZod;
export type UserAdherenceLogGetByIdInput = z.infer<typeof userAdherenceLogGetByIdZod>;

export const userAdherenceLogGetByUserZod = z.object({
	userId: z.uuid(),
});
export type UserAdherenceLogGetByUserInput = z.infer<typeof userAdherenceLogGetByUserZod>;

export const userAdherenceLogGetBySupplementZod = z.object({
	supplementId: z.uuid(),
});
export type UserAdherenceLogGetBySupplementInput = z.infer<typeof userAdherenceLogGetBySupplementZod>;

export const userAdherenceLogDeleteZod = userAdherenceLogAutoGeneratedZod;
export type UserAdherenceLogDeleteInput = z.infer<typeof userAdherenceLogDeleteZod>;
