import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { env } from './configs/env.config';

importScripts('https://cdn.jsdelivr.net/npm/@suprsend/web-sdk@4.0.0/public/serviceworker.min.js');
// @ts-ignore
initSuprSend(env.VITE_SUPRSEND_PUBLIC_API_KEY); // replace publicApiKey with your value

declare const self: ServiceWorkerGlobalScope;

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Inject the precache manifest (generated by the plugin)
precacheAndRoute(self.__WB_MANIFEST);

// Listen for SKIP_WAITING message from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    (self as ServiceWorkerGlobalScope).skipWaiting();
  }
});

registerRoute(
	new NavigationRoute(createHandlerBoundToURL('./index.html'))
)